apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: hfin
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
     - type: log
       paths:
        - /var/log/nginx/*.log
    
    output:
      logstash:
        hosts: ["{{ .Values.logstash.host }}:{{ .Values.logstash.port }}"]
        index: filebeat