apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "service.fullname" . }}-nignx-pv
  namespace: hfin
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/shared-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "service.fullname" . }}-nginx-pvc
  namespace: hfin
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany