# Generated by Django 5.0 on 2024-01-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0003_alter_expense_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="expense",
            unique_together=set(),
        ),
    ]
