# Generated by Django 5.0 on 2024-04-09 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0004_alter_expense_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=21,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
