[tool.poetry]
name = "default"
version = "0.1.0"
description = ""
authors = ["Artemiy_Shuvalov <shuvalovartal@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^5.0"
pandas = "^2.1.4"
aiochclient = "^2.5.1"
drf-yasg = "^1.21.7"
rest-framework-simplejwt = "^0.0.2"
djangorestframework-simplejwt = "^5.3.1"
django-admin = "^2.0.2"
uvicorn = "^0.25.0"
django-phonenumber-field = {extras = ["phonenumbers"], version = "^7.2.0"}
django-dynamic-fixture = "^4.0.1"
tqdm = "^4.66.1"
gunicorn = "^21.2.0"
pydantic = "^2.5.3"
requests = "^2.31.0"
scikit-learn = "^1.4.0"
openpyxl = "^3.1.2"
cleanweb = "^2.0"
django-simple-captcha = "^0.6.0"
celery = "^5.3.6"
redis = "^5.0.1"
psycopg2 = "^2.9.9"
django-redis = "^5.4.0"
django-clickhouse-backend = "^1.1.6"
setuptools = "^69.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
