---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}-elastic-search
  namespace: hfin
  labels:
    app: es-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  type: NodePort
  ports:
  - port: 9200
    protocol: TCP
    targetPort: http
    nodePort: 21645
  selector:
    app: es-logging