# Generated by Django 5.0 on 2023-12-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="done",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
