# Generated by Django 5.0 on 2023-12-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_expense_done"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="done",
        ),
    ]
