# Generated by Django 5.0 on 2024-01-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="target_name",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
