# Generated by Django 5.0 on 2024-03-25 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0003_transaction_target_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=21,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
