apiVersion: v1
data:
  nginx.conf: "server {\n    listen 80;\n    server_name hfin.ru;\n    access_log
    \ /var/log/nginx/example.log;\n    \n    \n    \n    location / {\n        proxy_pass http://{{ include "service.fullname" . }};\n        proxy_set_header
    Host {{ .Values.app.localhost }};\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_set_header
    X-Forwarded-For $proxy_add_x_forwarded_for;\n    }\n}"
kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}-nginx-conf