---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "service.fullname" . }}-ingress-nginx
spec:
  rules:
  - host: {{ .Values.app.devhost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "service.fullname" . }}-nginx
            port:
              number: 80
  ingressClassName: nginx
