# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "service.fullname" . }}-nginx-port
# spec:
#   selector:
#     app: {{ include "service.fullname" . }}-nginx-port
#   ports:
#   - port: 80
#     nodePort: 30080
#    name: http
#  type: NodePort
