---
apiVersion: v1
kind: Service
metadata:
  name:
    {{ include "service.fullname" . }}-nginx
spec:
  selector:
    app: {{ include "service.fullname" . }}-nginx
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP
