{{- if ne .Values.deployment "production" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}-clickhouse-replica-env
  labels:
    {{- include "service.labels" . | nindent 4 }}
data:
  # CLICKHOUSE settings
  HFIN_CLICKHOUSE_REPLICA_DATABASE: "{{ .Values.clickhouse_replica.db.name }}"
  HFIN_CLICKHOUSE_REPLICA_USER: "{{ .Values.clickhouse_replica.user.name }}"
  HFIN_CLICKHOUSE_REPLICA_PASSWORD: "{{ .Values.clickhouse_replica.user.password }}"
  HFIN_CLICKHOUSE_REPLICA_HOST: "{{ .Values.clickhouse_replica.host }}"
  HFIN_CLICKHOUSE_REPLICA_PORT: "{{ .Values.clickhouse_replica.port }}"

{{- end }}