# Generated by Django 5.0 on 2023-12-28 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=21)),
                (
                    "period_months",
                    models.CharField(
                        choices=[(1, " One"), (2, "Two"), (3, "Three")], max_length=1
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsersPayments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("done", models.BooleanField()),
                (
                    "tariff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="payment.tariff"
                    ),
                ),
            ],
        ),
    ]
