---
{{- if ne .Values.deployment "production" }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "service.fullname" . }}-migration-clickhouse
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  restartPolicy: Never
  initContainers:
    - name: {{ .Chart.Name }}-init-clickhouse
      image: cr.yandex/crp0civq107m91j8p8a2/base/await:latest
      {{- if eq .Values.deployment "local" }}
      imagePullPolicy: IfNotPresent
      {{- else }}
      imagePullPolicy: Always
      {{- end }}
      envFrom:
        - configMapRef:
            name: {{ include "service.fullname" . }}-clickhouse-env
      command: ['sh', '-c', 'await.sh $(CHANGESET_CLICKHOUSE_HOST) $(CHANGESET_CLICKHOUSE_PORT) 100000 10']
  containers:
    - name: {{ .Chart.Name }}
      image: "{{ .Values.image }}:{{ .Values.app.version | default .Chart.AppVersion }}"
      {{- if eq .Values.deployment "local" }}
      imagePullPolicy: IfNotPresent
      {{- else }}
      imagePullPolicy: Always
      {{- end }}
      envFrom:
        - configMapRef:
            name: {{ include "service.fullname" . }}-clickhouse-env
      command:
        - "poetry"
      args:
        - "run"
        - "alembic"
        - "-n"
        - "clickhouse_migrations"
        - "upgrade"
        - "head"
{{- end }}