{{- if ne .Values.deployment "production" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service.fullname" . }}-clickhouse
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "service.name" . }}-clickhouse
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "service.name" . }}-clickhouse
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "service.fullname" . }}-clickhouse
          image: clickhouse/clickhouse-server:{{ .Values.clickhouse.version | default "23.8" }}-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8123
            - containerPort: 9000
          resources:
            {{- toYaml .Values.clickhouse.resources | nindent 12 }}
{{- end }}