---
{{- if ne .Values.deployment "production" }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "service.fullname" . }}-migration-clickhouse
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  restartPolicy: Never
  initContainers:
    - name: {{ .Chart.Name }}-init-clickhouse
      image: busybox:1.35
      {{- if eq .Values.deployment "local" }}
      imagePullPolicy: IfNotPresent
      {{- else }}
      imagePullPolicy: Always
      {{- end }}
      envFrom:
        - configMapRef:
            name: {{ include "service.fullname" . }}-clickhouse-env
      command: ['sh', '-c', 'echo -e "Checking CH"; while ! nc -z $(HFIN_CLICKHOUSE_HOST) $(HFIN_CLICKHOUSE_PORT); do sleep 1; printf "-"; done; echo -e "  >> CH OK";']
  containers:
    - name: {{ .Chart.Name }}
      image: "{{ .Values.image }}:{{ .Values.app.version | default .Chart.AppVersion }}"
      {{- if eq .Values.deployment "local" }}
      imagePullPolicy: IfNotPresent
      {{- else }}
      imagePullPolicy: Always
      {{- end }}
      envFrom:
        - configMapRef:
            name: {{ include "service.fullname" . }}-clickhouse-env
      command:
        - "poetry"
      args:
        - "run"
        - "alembic"
        - "-n"
        - "clickhouse_migrations"
        - "upgrade"
        - "head"
{{- end }}