apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}-celery-worker
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "service.name" . }}-{{ .Values.deployment | default "dev" }}-celery-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
