apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}-app-env
  labels:
    {{- include "service.labels" . | nindent 4 }}
data:
  # APPLICATION settings
  APPLICATION_ENVIRONMENT:  "{{ .Values.deployment }}"
  APPLICATION_ROOT: "{{ .Values.app.root }}"
  APPLICATION_VERSION: "{{ .Values.app.version | default .Chart.AppVersion }}"
  CHANGESET_POSTGRESQL_PORT: "{{ .Values.postgresql.port }}"
  CHANGESET_POSTGRESQL_HOST: "{{ .Values.postgresql.host }}"
  CHANGESET_POSTGRESQL_PASSWORD: "{{ .Values.postgresql.user.password }}"
  CHANGESET_POSTGRESQL_USER: "{{ .Values.postgresql.user.name }}"
  CHANGESET_POSTGRESQL_DATABASE: "{{ .Values.postgresql.db.name }}"
  CHANGESET_CLICKHOUSE_HOST: "{{ .Values.clickhouse.host }}"
  CHANGESET_CLICKHOUSE_PORT: "{{ .Values.clickhouse.port }}"
  CHANGESET_REDIS_HOST: "{{ .Values.redis.host }}"
  CHANGESET_REDIS_PORT: "{{ .Values.redis.port }}"

  # CELERY settings
  CELERY_BROKER_URL: redis://redis:6379/0
  CELERY_RESULT_BACKEND: redis://redis:6379/0
