apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "service.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: {{ .Chart.Name }}-init-postgres
        image: cr.yandex/crp0civq107m91j8p8a2/base/await:latest
        {{- if eq .Values.deployment "local" }}
        imagePullPolicy: IfNotPresent
        {{- else }}
        imagePullPolicy: Always
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{ include "service.fullname" . }}-app-env
        command: ['sh', '-c', 'await.sh $(CHANGESET_POSTGRESQL_HOST) $(CHANGESET_POSTGRESQL_PORT) 100000 10']
      - name: {{ .Chart.Name }}-init-clickhouse
        image: cr.yandex/crp0civq107m91j8p8a2/base/await:latest
        {{- if eq .Values.deployment "local" }}
        imagePullPolicy: IfNotPresent
        {{- else }}
        imagePullPolicy: Always
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{ include "service.fullname" . }}-app-env
        command: ['sh', '-c', 'await.sh $(CHANGESET_CLICKHOUSE_HOST) $(CHANGESET_CLICKHOUSE_PORT) 100000 10']
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}:{{ .Values.app.version | default .Chart.AppVersion }}"
          {{- if eq .Values.deployment "local" }}
          imagePullPolicy: IfNotPresent
          {{- else }}
          imagePullPolicy: Always
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "service.fullname" . }}-app-env
          command:
            - "poetry"
          args:
            - "run"
            - "uvicorn"
            - "changeset.main:get_application"
            - "--host=0.0.0.0"
            - "--port=8080"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "{{ .Values.app.root }}/openapi.json"
              port: http
            initialDelaySeconds: 30
            periodSeconds: 300
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
