apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.deployment "local" }}
  type: NodePort
  {{- else}}
  type: ClusterIP
  {{- end }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
