"""
Django settings for hfin project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(7$ag!m$iq+c0k=mvifra#mauyu=2rg!gl!7pe3fi9km_m5*%&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
AUTH_USER_MODEL = 'user.User'

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = ['http://localhost', 'http://dev.hfin.local']


# 'rest_framework',
# 'rest_framework_simplejwt',
# 'drf_yasg',
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'captcha',
    'rest_framework',
    'rest_framework_simplejwt',
    'phonenumber_field',
    'drf_yasg',
    'income',
    'expense',
    'transaction',
    'user',
    'common_utils',
    'payment',
    'funds_director',
    'root',
    'notificator',
    'tasks'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'root.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'static/user/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'
ASGI_APPLICATION = 'asgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('HFIN_POSTGRESQL_DATABASE', 'postgres'),
        'USER': os.environ.get('HFIN_POSTGRESQL_USER', 'postgres'),
        'PASSWORD': os.environ.get('HFIN_POSTGRESQL_PASSWORD', 'postgres'),
        'HOST': os.environ.get('HFIN_POSTGRESQL_HOST', 'localhost'),
        'PORT': os.environ.get('HFIN_POSTGRESQL_PORT', '5432'),
        'priority': 1
    },
    'postgresql_replica_2': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('HFIN_POSTGRESQL_REPLICA_2_DATABASE', 'postgres'),
        'USER': os.environ.get('HFIN_POSTGRESQL_REPLICA_2_USER', 'postgres'),
        'PASSWORD': os.environ.get('HFIN_POSTGRESQL_REPLICA_2_PASSWORD', 'postgres'),
        'HOST': os.environ.get('HFIN_POSTGRESQL_REPLICA_2_HOST', 'localhost'),
        'PORT': os.environ.get('HFIN_POSTGRESQL_REPLICA_2_PORT', '5432'),
        'priority': 3
    },
    'postgresql_replica_1': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('HFIN_POSTGRESQL_REPLICA_1_DATABASE', 'postgres'),
        'USER': os.environ.get('HFIN_POSTGRESQL_REPLICA_1_USER', 'postgres'),
        'PASSWORD': os.environ.get('HFIN_POSTGRESQ_REPLICA_1L_PASSWORD', 'postgres'),
        'HOST': os.environ.get('HFIN_POSTGRESQL_REPLICA_1_HOST', 'localhost'),
        'PORT': os.environ.get('HFIN_POSTGRESQL_REPLICA_1_PORT', '5432'),
        'priority': 2
    },
    'clickhouse_replica': {
        'ENGINE': 'clickhouse_backend.backend',
        'NAME': os.environ.get('HFIN_CLICKHOUSE_REPLICA_DATABASE', 'default'),
        'USER': os.environ.get('HFIN_CLICKHOUSE_REPLICA_USER', 'default'),
        'PASSWORD': os.environ.get('HFIN_CLICKHOUSE_REPLICA_PASSWORD', ''),
        'HOST': os.environ.get('HFIN_CLICKHOUSE_REPLICA_HOST', 'localhost'),
        'PORT': os.environ.get('HFIN_CLICKHOUSE_REPLICA_PORT', '9000'),
        'priority': 5
    },
    'clickhouse': {
        'ENGINE': 'clickhouse_backend.backend',
        'NAME': os.environ.get('HFIN_CLICKHOUSE_DATABASE', 'default'),
        'USER': os.environ.get('HFIN_CLICKHOUSE_USER', 'default'),
        'PASSWORD': os.environ.get('HFIN_CLICKHOUSE_PASSWORD', ''),
        'HOST': os.environ.get('HFIN_CLICKHOUSE_HOST', 'localhost'),
        'PORT': os.environ.get('HFIN_CLICKHOUSE_PORT', '9000'),
        'priority': 4
    }
}
DATABASE_ROUTERS = ["root.dbrouters.DBRouter"]

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ru-Ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static', )

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST FRAMEWORK config
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    )
}

SMS_CONFIG = {
    'login': 'login',
    'password': 'password',
    'secret_key': 'secret_key',
    'url': 'url'
}

EMAIL_CONFIG = {
    'login': 'login',
    'password': 'password',
    'secret_key': 'secret_key',
    'url': 'https://www.yandex.ru'
}

PAYMENT_CONFIG = {
    'login': 'login',
    'password': 'password',
    'secret_key': 'secret_key',
    'url': 'url'
}


redis_cache_host = os.environ.get('HFIN_REDIS_CACHE_HOST', 'localhost')
redis_cache_port = os.environ.get('HFIN_REDIS_CACHE_PORT', '6379')
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{redis_cache_host}:{redis_cache_port}/',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}


# Models and tables lists for routing db
NEED_TABLE_ROUTING = [
    'income_income',
    'expense_expense',
    'payment_tariff',
    'payment_userspayments',
    'notificator_notification',
    'transaction_transaction'
    ]
TECH_TABLES = [
    'auth_group',
    'django_admin_log',
    'auth_permission',
    'captcha_captchastore',
    'django_session',
    'django_content_type',
]