[tool.poetry]
version = "1.0.0"
name = "changeset"
description = "Сервис миграции логов DML."
authors = ["Artemiy_Shuvalov <a.shuvalov@sailplay.ru>"]
license = "BSD"
readme = "README.md"
packages = [{include = "src/changeset"}]


[[tool.poetry.source]]
name = "sailplay-pypi"
url = "https://nexus.internal.sailplay.org/repository/Python-repo/simple"
priority = "explicit"


[tool.poetry.dependencies]
python = "^3.8.9"
fastapi = "0.63.0"
uvicorn = "^0.23.2"
requests = "^2.31.0"
httpx = "^0.24.1"
sentry-sdk = "1.0.0"
alembic = "1.12.1"
SQLAlchemy = "2.0.23"
clickhouse-sqlalchemy = "0.3.0"
fastapi-metrics = { version = "1.1.0", source = "sailplay-pypi" }
fastapi-security-headers = { version = "1.0.1", source = "sailplay-pypi" }
fastapi-application = { version = "1.0.1", source = "sailplay-pypi" }
fastapi-pg = { version = "^1.0.0", source = "sailplay-pypi" }
fastapi-sentry = { version = "^1.0.1", source = "sailplay-pypi" }
fastapi-clickhouse = { version = "1.0.0", source = "sailplay-pypi" }
fastapi-redis = { version = "^1.0.0", source = "sailplay-pypi" }
env-enum = { version = "^1.0.0", source = "sailplay-pypi" }
import-linter = "^1.12.1"
jsonlines = "^4.0.0"
celery = "^5.3.6"
redis = "4.0.0"
sqlparse = "0.3.1"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
pytest-mock = "^3.11.1"
pytest-asyncio = "^0.21.1"



[tool.poetry.group.flake.dependencies]
flake8 = "^6.1.0"
flake8-builtins = "^2.1.0"
flake8-docstrings = "^1.7.0"
flake8-quotes = "^3.3.2"


[tool.poetry.group.isort.dependencies]
isort = "^5.12.0"


[tool.poetry.group.bandit.dependencies]
bandit = "^1.7.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
