apiVersion: v1
name: changeset
version: 1.0.0
description: Migrator DML logs.
type: application
home: https://git.internal.sailplay.org/services/data_migratin/changeset
maintainers:
  - name: Aretmiy Shuvalov
    email: a.shuvalov@sailplay.ru
appVersion: 1.0.0
