image: cr.yandex/crp0civq107m91j8p8a2/services/changeset
deployment: staging
replicaCount: 1

app:
  name: changeset
  root: /services/changeset
  version: latest
  log_level: debug
  delay: 0

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

clickhouse:
  host: changeset-clickhouse
  port: 8123
  db:
    name: default
  user:
    name: default
    password: ''

redis:
  version: 7.0
  host: changeset-redis
  port: 6379
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

postgresql:
  version: 15
  host: changeset-postgresql
  port: 5432
  db:
    name: postgres
  user:
    name: postgres
    password: postgres

yandexos3:
  bucket_name: sp-test-app
  aws_access_key_id: YCAJEE2KeOBAiW9QcokRuufC_
  aws_secret_access_key: YCNdpu6ExIQlEopWtivZslxcRNfouX1IV7uFjaSF

autoscaling:
  enabled: false

sentry:
  enabled: false

statsd:
  enabled: false
