# Generated by Django 5.0 on 2023-12-26 11:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_confirm",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="is_phone_confirm",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="UserPhoneConfirmSMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "create_date",
                    models.DateField(
                        default=datetime.datetime(
                            2023,
                            12,
                            26,
                            11,
                            18,
                            31,
                            794819,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "expare_date",
                    models.DateField(
                        default=datetime.datetime(
                            2023,
                            12,
                            26,
                            11,
                            19,
                            31,
                            794819,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
