# Generated by Django 5.0 on 2023-12-26 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_is_email_confirm_user_is_phone_confirm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_email_confirm",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_phone_confirm",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="userphoneconfirmsms",
            name="create_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 12, 26, 11, 19, 33, 609846, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="userphoneconfirmsms",
            name="expare_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 12, 26, 11, 20, 33, 609846, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
