# Generated by Django 5.0 on 2024-01-22 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_userphoneconfirmsms_create_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="enable_subscription",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="userphoneconfirmsms",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 22, 18, 8, 47, 889770, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="userphoneconfirmsms",
            name="expare_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 22, 18, 9, 47, 889770, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
