# Generated by Django 5.0 on 2024-01-23 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_enable_subscription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userphoneconfirmsms",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 23, 16, 0, 28, 76307, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="userphoneconfirmsms",
            name="expare_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 23, 16, 1, 28, 76307, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
