# Generated by Django 5.0 on 2024-01-29 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_userphoneconfirmsms_create_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userphoneconfirmsms",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 29, 7, 4, 45, 967243, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="userphoneconfirmsms",
            name="expare_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 29, 7, 5, 45, 967243, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
