# Generated by Django 5.0 on 2024-02-01 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_userphoneconfirmsms_create_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="userphoneconfirmsms",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 1, 6, 41, 21, 709454, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="userphoneconfirmsms",
            name="expare_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 1, 6, 42, 21, 709454, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
