# Generated by Django 5.0 on 2024-03-25 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_alter_user_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userphoneconfirmsms",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 25, 7, 6, 13, 173089, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="userphoneconfirmsms",
            name="expare_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 25, 7, 7, 13, 173089, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
