# Generated by Django 5.0 on 2024-04-09 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_alter_userphoneconfirmsms_create_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userphoneconfirmsms",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 9, 15, 36, 41, 675730, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="userphoneconfirmsms",
            name="expare_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 9, 15, 37, 41, 675730, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
