# Generated by Django 5.0 on 2024-11-04 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_alter_userphoneconfirmsms_create_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userphoneconfirmsms",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 4, 14, 41, 23, 145813, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="userphoneconfirmsms",
            name="expare_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 4, 14, 42, 23, 145813, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
