apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "service.labels" . | nindent 4 }}
  name: {{ include "service.fullname" . }}-kibana
  namespace: hfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "service.name" . }}-elastic-search
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "service.name" . }}-elastic-search
          app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - image: kibana:7.8.0
        name: kibana
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        # livenessProbe:
        #   httpGet:
        #     port: http
        #     path: /status
        #   initialDelaySeconds: 40
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /status
        #     port: http
        #   initialDelaySeconds: 30
        #   periodSeconds: 10