apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kib-manual
  name: {{ include "service.fullname" . }}-kibana
  namespace: hfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kib-manual
  template:
    metadata:
      labels:
        app: kib-manual
    spec:
      containers:
      - image: kibana:7.8.0
        name: kibana
        volumeMounts:
          - name: kibana-configmap
            mountPath: /usr/share/kibana/config
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
      volumes:
      - name: kibana-configmap
        configMap:
          name: kibana-configmap
