apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}-kibana
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.deployment "local" }}
  type: NodePort
  {{- else}}
  type: ClusterIP
  {{- end }}
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}