apiVersion: v1
data:
  postgresql.conf: " \n wal_level = logical \n
    listen_addresses = '*' \n
    max_replication_slots = 50 \n
    max_logical_replication_workers = 20 \n
    max_worker_processes = 20 \n
    "

kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}-postgresql-conf-master-env
