---
{{- if ne .Values.deployment "production" }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "service.fullname" . }}-migration-postgresql
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  restartPolicy: Never
  initContainers:
      - name: {{ .Chart.Name }}-init-postgres
        image: busybox:1.35
        {{- if eq .Values.deployment "local" }}
        imagePullPolicy: IfNotPresent
        {{- else }}
        imagePullPolicy: Always
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{ include "service.fullname" . }}-postgresql-master-env
        command: ['sh', '-c', 'echo -e "Checking PG"; while ! nc -z $(HFIN_POSTGRESQL_HOST) $(HFIN_POSTGRESQL_PORT); do sleep 1; printf "-"; done; echo -e "  >> PG OK";']
  containers:
    - name: {{ .Chart.Name }}
      image: "{{ .Values.image }}:{{ .Values.app.version | default .Chart.AppVersion }}"
      {{- if eq .Values.deployment "local" }}
      imagePullPolicy: IfNotPresent
      {{- else }}
      imagePullPolicy: Always
      {{- end }}
      envFrom:
        - configMapRef:
            name: {{ include "service.fullname" . }}-postgresql-master-env
      command: ["sh", "-c"]
      args:
      - |
        poetry run python manage.py makemigrations
        poetry run python manage.py migrate --database=default
        poetry run python manage.py set_schema_replication_on_clickhouse
        poetry run python manage.py custom_createsuperuser +79999999999 example@example.com test
        poetry run python manage.py generate_fixtures 100
{{- end }}