# Generated by Django 5.0 on 2024-01-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="user_id",
            field=models.BigIntegerField(),
        ),
    ]
