# Generated by Django 5.0 on 2024-04-09 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="income",
            name="done",
        ),
        migrations.AlterField(
            model_name="income",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=21,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
